"use client"

import { useState, useCallback } from "react"
import { DashboardSidebar, type TabId } from "@/components/dashboard/sidebar"
import { DashboardHeader } from "@/components/dashboard/header"
import { MetricCards } from "@/components/dashboard/metric-cards"
import { AstanaMap } from "@/components/dashboard/astana-map"
import { AIVisionWidget } from "@/components/dashboard/ai-vision-widget"
import { AlertNotificationPanel, type AlertNotification } from "@/components/dashboard/alert-notification"
import { ReportModal } from "@/components/dashboard/report-modal"
import { cn } from "@/lib/utils"
import { Cpu, FileText, Construction, Download, FileBarChart, Calendar } from "lucide-react"

function PlaceholderPage({ title, icon: Icon }: { title: string; icon: typeof Cpu }) {
  return (
    <div className="h-full flex flex-col items-center justify-center text-center p-8">
      <div className="w-20 h-20 rounded-2xl bg-primary/10 flex items-center justify-center mb-6 glow-neon-green">
        <Icon className="w-10 h-10 text-primary" />
      </div>
      <h2 className="text-2xl font-bold text-foreground mb-2">{title}</h2>
      <p className="text-muted-foreground max-w-md">
        This section is under development. Check back soon for updates.
      </p>
      <div className="flex items-center gap-2 mt-6 text-sm text-muted-foreground">
        <Construction className="w-4 h-4" />
        <span>Coming Soon</span>
      </div>
    </div>
  )
}

interface ReportsPageProps {
  onOpenReport: () => void
}

function ReportsPage({ onOpenReport }: ReportsPageProps) {
  const currentDate = new Date()
  const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ]

  const reports = [
    {
      title: "Monthly Water Quality Report",
      description: "Comprehensive analysis of water parameters, sensor data, and AI recommendations",
      month: monthNames[currentDate.getMonth()],
      year: currentDate.getFullYear(),
      type: "Full Report",
      available: true,
    },
    {
      title: "Weekly Summary",
      description: "Quick overview of key metrics and alerts from the past 7 days",
      month: monthNames[currentDate.getMonth()],
      year: currentDate.getFullYear(),
      type: "Summary",
      available: true,
    },
    {
      title: "Microplastic Analysis",
      description: "Detailed breakdown of microplastic detection by type, size, and location",
      month: monthNames[currentDate.getMonth()],
      year: currentDate.getFullYear(),
      type: "Specialized",
      available: false,
    },
    {
      title: "Sensor Performance",
      description: "Calibration status, uptime metrics, and maintenance schedule",
      month: monthNames[currentDate.getMonth()],
      year: currentDate.getFullYear(),
      type: "Technical",
      available: false,
    },
  ]

  return (
    <div className="h-full flex flex-col p-6">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-foreground mb-2">Reports & Analytics</h2>
        <p className="text-muted-foreground">
          Access detailed water quality reports and analytics generated by Tunyq AI system
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {reports.map((report, index) => (
          <div
            key={index}
            className={cn(
              "relative bg-card rounded-xl border border-border p-5 overflow-hidden transition-all duration-300",
              report.available 
                ? "hover:border-primary/50 cursor-pointer group" 
                : "opacity-60"
            )}
            onClick={() => report.available && onOpenReport()}
          >
            {/* Background glow effect */}
            {report.available && (
              <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
            )}

            <div className="relative">
              <div className="flex items-start justify-between mb-3">
                <div className="w-12 h-12 rounded-xl bg-primary/15 flex items-center justify-center glow-neon-green">
                  <FileBarChart className="w-6 h-6 text-primary" />
                </div>
                <div className={cn(
                  "px-2.5 py-1 rounded-full text-xs font-medium",
                  report.available 
                    ? "bg-primary/15 text-primary"
                    : "bg-muted text-muted-foreground"
                )}>
                  {report.available ? "Available" : "Coming Soon"}
                </div>
              </div>

              <h3 className="text-lg font-semibold text-foreground mb-1">{report.title}</h3>
              <p className="text-sm text-muted-foreground mb-4">{report.description}</p>

              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4 text-xs text-muted-foreground">
                  <div className="flex items-center gap-1">
                    <Calendar className="w-3.5 h-3.5" />
                    <span>{report.month} {report.year}</span>
                  </div>
                  <div className="px-2 py-0.5 rounded bg-secondary text-secondary-foreground">
                    {report.type}
                  </div>
                </div>

                {report.available && (
                  <button className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary/15 text-primary text-sm font-medium hover:bg-primary/25 transition-colors">
                    <Download className="w-3.5 h-3.5" />
                    <span>Open</span>
                  </button>
                )}
              </div>
            </div>

            {/* Bottom accent line */}
            <div className={cn(
              "absolute bottom-0 left-0 right-0 h-0.5",
              report.available ? "bg-primary/50" : "bg-muted"
            )} />
          </div>
        ))}
      </div>
    </div>
  )
}

export default function DashboardPage() {
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false)
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [activeTab, setActiveTab] = useState<TabId>("overview")
  const [notifications, setNotifications] = useState<AlertNotification[]>([])
  const [simulatedAlertSensorId, setSimulatedAlertSensorId] = useState<string | null>(null)
  const [reportModalOpen, setReportModalOpen] = useState(false)

  const handleSimulateAlert = useCallback(() => {
    // Trigger alert on Sensor #07 (which was previously green/normal)
    const targetSensorId = "1" // Sensor #07
    
    setSimulatedAlertSensorId(targetSensorId)
    
    // Add critical notification
    const newNotification: AlertNotification = {
      id: `alert-${Date.now()}`,
      title: "CRITICAL ALERT",
      message: "Attention! Critical PET concentration level detected at Sensor #07. AI system identified dangerous microplastic levels.",
      timestamp: new Date(),
      severity: "critical",
    }
    
    setNotifications(prev => [newNotification, ...prev])
    
    // Auto-dismiss after 15 seconds
    setTimeout(() => {
      setNotifications(prev => prev.filter(n => n.id !== newNotification.id))
    }, 15000)
  }, [])

  const handleDismissNotification = useCallback((id: string) => {
    setNotifications(prev => prev.filter(n => n.id !== id))
  }, [])

  const handleOpenReport = useCallback(() => {
    setReportModalOpen(true)
  }, [])

  const renderContent = () => {
    switch (activeTab) {
      case "overview":
        return (
          <div className="space-y-6 animate-fade-in">
            <MetricCards onOpenReport={handleOpenReport} />
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
              <div className="h-[450px] lg:h-[500px]">
                <AstanaMap simulatedAlertSensorId={simulatedAlertSensorId} />
              </div>
              <div className="h-[450px] lg:h-[500px]">
                <AIVisionWidget />
              </div>
            </div>
          </div>
        )
      case "map":
        return (
          <div className="h-[calc(100vh-120px)] lg:h-[calc(100vh-80px)] animate-fade-in">
            <AstanaMap fullscreen simulatedAlertSensorId={simulatedAlertSensorId} />
          </div>
        )
      case "ai-analytics":
        return (
          <div className="h-[calc(100vh-120px)] lg:h-[calc(100vh-80px)] animate-fade-in">
            <AIVisionWidget fullscreen />
          </div>
        )
      case "devices":
        return (
          <div className="h-[calc(100vh-120px)] lg:h-[calc(100vh-80px)] animate-fade-in">
            <div className="h-full rounded-xl bg-card border border-border">
              <PlaceholderPage title="Device Management" icon={Cpu} />
            </div>
          </div>
        )
      case "reports":
        return (
          <div className="h-[calc(100vh-120px)] lg:h-[calc(100vh-80px)] animate-fade-in">
            <div className="h-full rounded-xl bg-card border border-border overflow-hidden">
              <ReportsPage onOpenReport={handleOpenReport} />
            </div>
          </div>
        )
      default:
        return null
    }
  }

  return (
    <div className="min-h-screen bg-background">
      <DashboardSidebar
        collapsed={sidebarCollapsed}
        onCollapsedChange={setSidebarCollapsed}
        mobileOpen={mobileMenuOpen}
        onMobileOpenChange={setMobileMenuOpen}
        activeTab={activeTab}
        onTabChange={setActiveTab}
      />

      <div
        className={cn(
          "min-h-screen transition-all duration-300",
          "lg:pl-64",
          sidebarCollapsed && "lg:pl-16"
        )}
      >
        <DashboardHeader onSimulateAlert={handleSimulateAlert} />

        <main className="p-4 lg:p-6 pt-20 lg:pt-6">
          {renderContent()}
        </main>
      </div>

      {/* Alert Notification Panel */}
      <AlertNotificationPanel 
        notifications={notifications} 
        onDismiss={handleDismissNotification} 
      />

      {/* Report Modal */}
      <ReportModal 
        isOpen={reportModalOpen} 
        onClose={() => setReportModalOpen(false)} 
      />
    </div>
  )
}
